import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, SafeAreaView, TouchableOpacity, KeyboardAvoidingView, Platform, ScrollView, Modal, TextInput } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { theme } from '../utils/theme';
import InputField from '../components/InputField';
import PrimaryButton from '../components/PrimaryButton';
import { apiCrearUsuario } from '../services/api';

export default function SignupScreen({ navigation }) {
    const [nombre, setNombre] = useState('');
    const [apellido, setApellido] = useState('');
    const [usuario, setUsuario] = useState('');
    const [municipio, setMunicipio] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [acceptedTerms, setAcceptedTerms] = useState(false);
    const [isMunicipioModalVisible, setIsMunicipioModalVisible] = useState(false);
    const [autoGeneratedUsername, setAutoGeneratedUsername] = useState('');
    const [municipioSearch, setMunicipioSearch] = useState('');
    const [isTermsModalVisible, setIsTermsModalVisible] = useState(false);
    const [secureText, setSecureText] = useState(true);
    const [isSubmitting, setIsSubmitting] = useState(false);

    const MUNICIPIOS_TRUJILLO = [
        'Trujillo',
        'Valera',
        'Boconó',
        'Carvajal',
        'Escuque',
        'Motatán',
        'Pampán',
        'Pampanito',
        'La Ceiba',
        'Miranda',
        'Monte Carmelo',
        'Sucre',
        'Urdaneta',
    ];

    const normalizarTexto = (texto) => {
        return texto
            .toLowerCase()
            .normalize('NFD')
            .replace(/[\u0300-\u036f]/g, '')
            .replace(/[^a-z0-9]/g, '');
    };

    const usuarioEsValido = () => {
        const limpio = usuario.trim();
        if (!limpio) return false;
        if (limpio.length < 4) return false;
        return /^[a-z0-9]+$/.test(limpio);
    };

    const isNextDisabled =
        !nombre.trim() ||
        !apellido.trim() ||
        !municipio.trim() ||
        !password.trim() ||
        !confirmPassword.trim() ||
        !usuarioEsValido() ||
        !acceptedTerms;

    useEffect(() => {
        const base = `${normalizarTexto(nombre)}${normalizarTexto(apellido)}`;
        if (!base) {
            setAutoGeneratedUsername('');
            if (!usuario) setUsuario('');
            return;
        }
        const nuevoAuto = base;
        setAutoGeneratedUsername(nuevoAuto);
        if (!usuario || usuario === autoGeneratedUsername) {
            setUsuario(nuevoAuto);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [nombre, apellido]);

    const simpleHash = (text) => {
        // Hash muy sencillo SOLO para demo. En producción usa bcrypt/argon2 en el backend.
        return `local_${text.split('').reverse().join('')}`;
    };

    const handleNext = async () => {
        if (password !== confirmPassword) {
            alert('Las contraseñas no coinciden');
            return;
        }
        if (password.length < 6) {
            alert('La contraseña es muy corta');
            return;
        }

        try {
            setIsSubmitting(true);
            const passwordHash = simpleHash(password);

            const nuevoUsuario = await apiCrearUsuario({
                nombre,
                apellido,
                usuario,
                municipioNombre: municipio,
                passwordHash,
                telefono: null,
                cedula: null,
            });

            navigation.navigate('Verify', { usuarioId: nuevoUsuario.id });
        } catch (error) {
            console.error(error);
            alert('Ocurrió un error al crear tu cuenta. Intenta de nuevo.');
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <SafeAreaView style={styles.safeArea}>
            <KeyboardAvoidingView
                behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
                style={{ flex: 1 }}
            >
                <ScrollView contentContainerStyle={styles.container}>
                    <View style={styles.header}>
                        <Text style={styles.logo}>Nex<Text style={styles.logoAccent}>Store</Text></Text>
                        <Text style={styles.title}>Crea tu Cuenta</Text>
                        <Text style={styles.subtitle}>Paso 1: Información Personal</Text>
                    </View>

                    <View style={styles.formContainer}>
                        <View style={styles.row}>
                            <InputField
                                label="Nombre"
                                placeholder=""
                                value={nombre}
                                onChangeText={setNombre}
                                containerStyle={{ flex: 1, marginRight: 10 }}
                            />
                            <InputField
                                label="Apellido"
                                placeholder=""
                                value={apellido}
                                onChangeText={setApellido}
                                containerStyle={{ flex: 1 }}
                            />
                        </View>

                        <InputField
                            label="Usuario"
                            icon="at"
                            placeholder="Se genera a partir de tu nombre, puedes ajustarlo"
                            value={usuario}
                            onChangeText={setUsuario}
                        />

                        {!!autoGeneratedUsername && (
                            <Text style={styles.usernameHelper}>
                                Tu usuario sugerido es <Text style={styles.usernameCode}>{autoGeneratedUsername}</Text>. Puedes modificarlo si quieres.
                            </Text>
                        )}

                        {usuario.trim() !== '' && !usuarioEsValido() && (
                            <Text style={styles.usernameError}>
                                Usa al menos 4 caracteres, solo letras minúsculas y números, sin espacios.
                            </Text>
                        )}

                        <TouchableOpacity
                            activeOpacity={0.8}
                            onPress={() => setIsMunicipioModalVisible(true)}
                            style={styles.selectContainer}
                        >
                            <Text style={styles.selectLabel}>Municipio</Text>
                            <View style={styles.selectField}>
                                <Ionicons name="map" size={18} color={theme.colors.textMuted} style={{ marginRight: 8 }} />
                                <Text
                                    style={[
                                        styles.selectText,
                                        !municipio && { color: theme.colors.textMuted },
                                    ]}
                                >
                                    {municipio || 'Selecciona tu municipio'}
                                </Text>
                                <Ionicons name="chevron-down" size={18} color={theme.colors.textMuted} />
                            </View>
                        </TouchableOpacity>

                        <InputField
                            label="Contraseña"
                            icon="lock-closed"
                            placeholder="Mínimo 6 caracteres"
                            value={password}
                            onChangeText={setPassword}
                            secureTextEntry={secureText}
                            onTogglePassword={() => setSecureText(!secureText)}
                        />

                        <InputField
                            label="Confirmar Contraseña"
                            icon="shield-checkmark"
                            placeholder="Repite tu contraseña"
                            value={confirmPassword}
                            onChangeText={setConfirmPassword}
                            secureTextEntry={true}
                            containerStyle={{ marginBottom: 30 }}
                        />

                        <View style={styles.termsContainer}>
                            <TouchableOpacity
                                onPress={() => setAcceptedTerms(!acceptedTerms)}
                                style={styles.checkbox}
                                activeOpacity={0.8}
                            >
                                {acceptedTerms && (
                                    <Ionicons
                                        name="checkmark"
                                        size={16}
                                        color={theme.colors.white}
                                    />
                                )}
                            </TouchableOpacity>
                            <Text style={styles.termsText}>
                                Acepto los{' '}
                                <Text style={styles.linkText} onPress={() => setIsTermsModalVisible(true)}>
                                    Términos y Condiciones
                                </Text>
                            </Text>
                        </View>

                        <PrimaryButton
                            title="Siguiente Paso "
                            icon={<Ionicons name="arrow-forward" size={20} color={theme.colors.white} />}
                            onPress={handleNext}
                            disabled={isNextDisabled || isSubmitting}
                        />
                    </View>

                    <View style={styles.footer}>
                        <Text style={styles.footerText}>¿Ya tienes una cuenta? </Text>
                        <TouchableOpacity onPress={() => navigation.navigate('Login')}>
                            <Text style={styles.linkText}>Inicia sesión</Text>
                        </TouchableOpacity>
                    </View>
                </ScrollView>
            </KeyboardAvoidingView>

            <Modal
                visible={isMunicipioModalVisible}
                animationType="slide"
                transparent
                onRequestClose={() => setIsMunicipioModalVisible(false)}
            >
                <View style={styles.modalOverlay}>
                    <View style={styles.modalContent}>
                        <Text style={styles.modalTitle}>Selecciona tu municipio</Text>
                        <TextInput
                            style={styles.modalSearchInput}
                            placeholder="Buscar municipio..."
                            placeholderTextColor={theme.colors.textMuted}
                            value={municipioSearch}
                            onChangeText={setMunicipioSearch}
                        />
                        <ScrollView>
                            {MUNICIPIOS_TRUJILLO.filter((m) =>
                                m.toLowerCase().includes(municipioSearch.toLowerCase()),
                            ).map((item) => (
                                <TouchableOpacity
                                    key={item}
                                    style={styles.modalItem}
                                    onPress={() => {
                                        setMunicipio(item);
                                        setIsMunicipioModalVisible(false);
                                    }}
                                >
                                    <View style={styles.modalItemRow}>
                                        <Text style={styles.modalItemText}>{item}</Text>
                                        {municipio === item && (
                                            <Ionicons
                                                name="checkmark-circle"
                                                size={20}
                                                color={theme.colors.primary}
                                            />
                                        )}
                                    </View>
                                </TouchableOpacity>
                            ))}
                        </ScrollView>
                        <TouchableOpacity
                            style={styles.modalCloseButton}
                            onPress={() => setIsMunicipioModalVisible(false)}
                        >
                            <Text style={styles.modalCloseText}>Cerrar</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </Modal>

            <Modal
                visible={isTermsModalVisible}
                animationType="slide"
                transparent
                onRequestClose={() => setIsTermsModalVisible(false)}
            >
                <View style={styles.modalOverlay}>
                    <View style={styles.modalContent}>
                        <Text style={styles.modalTitle}>Términos y Condiciones</Text>
                        <ScrollView>
                            <Text style={styles.termsBodyText}>
                                Esta aplicación tiene como objetivo conectar emprendedores y clientes dentro
                                del estado Trujillo. El uso de la plataforma implica un compromiso de respetar
                                a otros usuarios, no publicar contenido ilegal o inapropiado y proporcionar
                                datos reales al momento de verificar tu cuenta para compras.
                            </Text>
                            <Text style={styles.termsBodyText}>
                                Al continuar, aceptas que el equipo administrador puede revisar y aprobar
                                tus publicaciones, así como suspender cuentas que incumplan las reglas
                                de uso. Puedes solicitar la eliminación de tus datos escribiéndonos
                                a los canales oficiales definidos por los administradores.
                            </Text>
                        </ScrollView>
                        <TouchableOpacity
                            style={styles.modalCloseButton}
                            onPress={() => {
                                setAcceptedTerms(true);
                                setIsTermsModalVisible(false);
                            }}
                        >
                            <Text style={styles.modalCloseText}>Aceptar y continuar</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </Modal>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.colors.white },
    container: { flexGrow: 1, paddingHorizontal: 30, paddingTop: 60, paddingBottom: 40, justifyContent: 'center' },
    header: { alignItems: 'center', marginBottom: 40 },
    logo: { fontSize: 28, fontFamily: theme.fonts.bold, color: theme.colors.textMain, marginBottom: 15 },
    logoAccent: { color: theme.colors.primary },
    title: { fontSize: 24, fontFamily: theme.fonts.bold, color: theme.colors.textMain, marginBottom: 8 },
    subtitle: { fontSize: 15, fontFamily: theme.fonts.regular, color: theme.colors.textMuted },
    formContainer: { width: '100%' },
    row: { flexDirection: 'row', width: '100%' },
    footer: { flexDirection: 'row', justifyContent: 'center', marginTop: 30 },
    footerText: { fontFamily: theme.fonts.regular, color: theme.colors.textMain },
    linkText: { fontFamily: theme.fonts.semiBold, color: theme.colors.primary, textDecorationLine: 'underline' },
    usernameHelper: {
        marginTop: -10,
        marginBottom: 10,
        fontSize: 12,
        fontFamily: theme.fonts.regular,
        color: theme.colors.textMuted,
    },
    usernameCode: {
        fontFamily: theme.fonts.semiBold,
        color: theme.colors.primary,
    },
    usernameError: {
        marginTop: -8,
        marginBottom: 10,
        fontSize: 12,
        fontFamily: theme.fonts.regular,
        color: 'red',
    },
    selectContainer: { marginBottom: 16 },
    selectLabel: { marginBottom: 8, fontSize: 14, fontFamily: theme.fonts.semiBold, color: theme.colors.textMuted },
    selectField: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.white,
    },
    selectText: {
        flex: 1,
        fontFamily: theme.fonts.regular,
        color: theme.colors.textMain,
        fontSize: 15,
    },
    termsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: theme.colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
        backgroundColor: theme.colors.primary,
    },
    termsText: {
        flex: 1,
        fontFamily: theme.fonts.regular,
        color: theme.colors.textMain,
        fontSize: 13,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        maxHeight: '60%',
        backgroundColor: theme.colors.white,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
    },
    modalTitle: {
        fontFamily: theme.fonts.bold,
        fontSize: 18,
        marginBottom: 12,
        color: theme.colors.textMain,
    },
    modalSearchInput: {
        marginBottom: 10,
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
        fontFamily: theme.fonts.regular,
        fontSize: 14,
        color: theme.colors.textMain,
    },
    modalItem: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    modalItemRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modalItemText: {
        fontFamily: theme.fonts.regular,
        fontSize: 15,
        color: theme.colors.textMain,
    },
    modalCloseButton: {
        marginTop: 10,
        alignSelf: 'center',
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 999,
        backgroundColor: theme.colors.backgroundApp,
    },
    modalCloseText: {
        fontFamily: theme.fonts.medium,
        color: theme.colors.textMain,
    },
});
